const caseStudies = {
    shop: { category: "E-COMMERCE · DEMO", title: "Modern Shop", summary: "Учебная витрина: поиск товаров, фильтры категорий и корзина с изменением количества, расчётом суммы и сохранением в localStorage.", tech: ["HTML", "CSS", "JavaScript"], demo: "shop.html", challenge: "Помочь пользователю найти товар, собрать корзину и видеть сумму после каждого изменения.", solution: "На JavaScript реализованы поиск по названию, описанию и категории, фильтры, добавление и удаление товаров, изменение количества и пересчёт суммы. Корзина сохраняется в localStorage.", result: "Пользователь может найти товар, изменить состав корзины и восстановить её после перезагрузки. Оформление заказа — демонстрация без оплаты и отправки заказа на сервер.", features: ["Поиск по названию, описанию и категории", "Фильтры категорий", "Сортировка по цене и названию", "Добавление и удаление товаров", "Изменение количества и расчёт суммы", "Сохранение корзины в localStorage", "Демонстрационное оформление заказа"] },
    planner: {"category":"REACT APP","title":"Планировщик задач на React","summary":"React-планировщик с тремя страницами, приоритетами, сроками, поиском, сменой темы и импортом примеров из API.","challenge":"React-планировщик с тремя страницами, приоритетами, сроками, поиском, сменой темы и импортом примеров из API.","solution":"Компоненты получают props, useState управляет данными, useEffect сохраняет их и обрабатывает API-запросы. Context разделяет тему и задачи между страницами, React Router организует три маршрута. Форма поддерживает приоритеты, сроки и валидацию.","result":"Задачи и тема сохраняются локально. Примеры загружаются из DummyJSON с обработкой ошибок и отменой запросов. Повторный импорт исключён; личные задачи не отправляются в API.","features":["React-компоненты и props", "Строгая проверка типов TypeScript","State, useState и useEffect","Общие данные и тема через Context","Три страницы с React Router","Форма с приоритетом и сроком","Поиск и фильтры","Импорт примеров из API","Локальное хранение и обработка ошибок"],"tech":["React","TypeScript","React Router","CSS","Vite","API"],"demo":"react-planner/"},
    dashboard: { category: "DASHBOARD · DEMO", title: "Admin Dashboard", summary: "Демо dashboard: фильтрация за 7/30/90 дней, пересчёт диаграммы и показателей, список заказов и экспорт CSV.", tech: ["HTML", "CSS", "JavaScript"], demo: "dashboard.html", challenge: "Разместить показатели, график продаж и заказы в понятной структуре для быстрого просмотра.", solution: "JavaScript создаёт набор демонстрационных заказов. Выбор 7/30/90 дней фильтрует заказы и пересчитывает показатели и диаграмму. Реализованы просмотр полного списка, экспорт CSV и сохранение темы.", result: "Диаграмма, показатели и таблица обновляются из одного набора данных за выбранный период. Заказы можно скачать в CSV. Данные демонстрационные и не загружаются с сервера.", features: ["Карточки ключевых показателей", "Столбчатая диаграмма продаж", "Индикаторы прогресса", "Таблица заказов", "Переключение светлой и тёмной темы", "Фильтрация по периоду и экспорт CSV", "Фильтрация по статусу заказа"] },
    weather: {"category":"WEATHER · API","title":"Приложение погоды","summary":"Погода с поиском города, текущими показателями и пятидневным прогнозом из Open-Meteo API.","tech":["HTML","CSS","JavaScript","API"],"demo":"weather.html","challenge":"Обрабатывать ввод города и показывать понятные погодные показатели и сообщения об ошибках.","solution":"Geocoding API находит координаты города, затем загружаются текущие показатели и прогноз на пять дней. Реализованы состояние загрузки, обработка ошибок и отмена устаревших запросов.","result":"Показатели и прогноз поступают из внешнего API. При ошибке связи отображается сообщение, а демонстрационные значения не выдаются за текущую погоду.","features":["Поиск города через Geocoding API","Текущие погодные показатели","Прогноз на пять дней","Загрузка и обработка ошибок","Отмена устаревших запросов","Сохранение последнего города"]},
    music: {"category":"WEB AUDIO · DEMO","title":"Музыкальный плеер","summary":"Web Audio плеер: три синтезированные мелодии, настоящая пауза и продолжение, перемотка и регулировка громкости.","tech":["HTML","CSS","JavaScript","Web Audio"],"demo":"music.html","challenge":"Создать звук в браузере и связать выбор мелодии с элементами интерфейса.","solution":"Мелодии создаются в AudioBuffer. BufferSource начинает воспроизведение с выбранной позиции, пауза останавливает звук, а продолжение возобновляет его с того же места. Добавлены выбор из списка, управление клавиатурой и громкостью.","result":"Время связано с часами AudioContext. Пауза и ползунок управляют звуком, после окончания начинается следующая мелодия. Используются синтезированные мелодии без внешних музыкальных файлов.","features":["Синтез звука Web Audio","Настоящая пауза и продолжение","Перемотка звука","Выбор и переход между мелодиями","Регулировка громкости","Управление клавиатурой"]}
};

const projectId = new URLSearchParams(window.location.search).get("project");
const selectedLanguage = localStorage.getItem("portfolio-language") || "ru";
const localizedContent = {
    hy: {
        labels: ["← Վերադառնալ նախագծերին", "Բացել demo-ն ↗", "Խնդիր", "Լուծում", "Արդյունք", "Իրականացված հնարավորություններ"],
        shop: { category: "E-COMMERCE · DEMO", title: "Modern Shop", summary: "Ուսումնական խանութ՝ ապրանքների որոնմամբ, կատեգորիաների զտմամբ և զամբյուղով՝ քանակի փոփոխություն, գումարի հաշվարկ ու պահպանում localStorage-ում։", challenge: "Օգնել օգտատիրոջը գտնել ապրանքը, կազմել զամբյուղը և ամեն փոփոխությունից հետո տեսնել ընդհանուր գումարը։", solution: "JavaScript-ով իրականացվել են որոնում ըստ անվան, նկարագրության և կատեգորիայի, զտիչներ, ապրանքների ավելացում ու հեռացում, քանակի փոփոխություն և գումարի վերահաշվարկ։ Զամբյուղը պահվում է localStorage-ում։", result: "Օգտատերը կարող է գտնել ապրանքը, փոխել զամբյուղի կազմը և վերականգնել այն էջը թարմացնելուց հետո։ Պատվերի ձևավորումը ցուցադրական է՝ առանց վճարման և պատվերը սերվեր ուղարկելու։", features: ["Որոնում ըստ անվան, նկարագրության և կատեգորիայի", "Կատեգորիաների զտիչներ", "Դասավորում ըստ գնի և անվան", "Ապրանքների ավելացում ու հեռացում", "Քանակի փոփոխություն և գումարի հաշվարկ", "Զամբյուղի պահպանում localStorage-ում", "Պատվերի ցուցադրական ձևավորում"] },
        planner: {"category":"REACT APP","title":"React առաջադրանքների պլանավորիչ","summary":"React պլանավորիչ՝ երեք էջով, կարևորությամբ ու ժամկետներով, որոնմամբ, թեմայի փոխարկմամբ և API-ից օրինակների ներմուծմամբ։","challenge":"React պլանավորիչ՝ երեք էջով, կարևորությամբ ու ժամկետներով, որոնմամբ, թեմայի փոխարկմամբ և API-ից օրինակների ներմուծմամբ։","solution":"Առանձին բաղադրիչները ստանում են props, useState-ը կառավարում է տվյալները, իսկ useEffect-ը պահպանում է դրանք և մշակում API հարցումները։ Context-ը կիսում է թեման ու առաջադրանքները, React Router-ը կազմակերպում է երեք էջերի անցումները։ Ձևն ունի կարևորություն, ժամկետ և վավերացում։","result":"Առաջադրանքներն ու թեման պահվում են բրաուզերում։ Օրինակները բեռնվում են DummyJSON-ից՝ սխալների մշակմամբ և հարցումների չեղարկմամբ։ Կրկնվող ներմուծումը կանխվում է, անձնական առաջադրանքները API չեն ուղարկվում։","features":["React բաղադրիչներ և props", "TypeScript-ի խիստ տիպային ստուգում","State, useState և useEffect","Context-ով ընդհանուր տվյալներ և թեմա","React Router-ով երեք էջ","Կարևորության և ժամկետի ձև","Որոնում և զտիչներ","API-ից օրինակների ներմուծում","Տեղական պահպանում և սխալների մշակում"]},
        dashboard: { category: "DASHBOARD · DEMO", title: "Admin Dashboard", summary: "Ցուցադրական dashboard՝ 7/30/90 օրվա զտմամբ, վերահաշվարկվող գրաֆիկով ու ցուցանիշներով, պատվերների ցանկով և CSV ներբեռնմամբ։", challenge: "Ցուցանիշները, վաճառքների գրաֆիկն ու պատվերները դասավորել հստակ կառուցվածքով՝ արագ դիտելու համար։", solution: "JavaScript-ով ստեղծվում է ցուցադրական պատվերների հավաքածու։ 7/30/90 օրվա ընտրությամբ զտվում են պատվերները, հաշվարկվում են ցուցանիշներն ու գրաֆիկի արժեքները։ Ավելացվել են ամբողջ ցանկի բացում, CSV ներբեռնում և թեմայի պահպանում։", result: "Ընտրված ժամանակահատվածի համար գրաֆիկը, ցուցանիշներն ու աղյուսակը թարմացվում են նույն տվյալներից։ Կարելի է ներբեռնել համապատասխան պատվերները CSV ձևաչափով։ Տվյալները ցուցադրական են և սերվերից չեն ստացվում։", features: ["Հիմնական ցուցանիշների քարտեր", "Վաճառքների սյունակային գրաֆիկ", "Առաջընթացի ցուցիչներ", "Պատվերների աղյուսակ", "Բաց ու մուգ թեմաների փոխարկում", "Ժամանակահատվածով զտում և CSV ներբեռնում", "Պատվերների կարգավիճակով զտում"] },
        weather: {"category":"WEATHER · API","title":"Եղանակի հավելված","summary":"Եղանակի հավելված՝ քաղաքների որոնմամբ, ընթացիկ տվյալներով և հնգօրյա կանխատեսմամբ՝ Open-Meteo API-ից։","challenge":"Մշակել քաղաքի մուտքագրումը և հստակ ցուցադրել եղանակի տվյալներն ու սխալի հաղորդագրությունները։","solution":"Քաղաքի անունը վերածվում է կոորդինատների Geocoding API-ով։ Այնուհետև բեռնվում են ընթացիկ եղանակային ցուցանիշներն ու հնգօրյա կանխատեսումը։ Իրականացվել են բեռնման վիճակ, սխալների մշակում և հին հարցումների չեղարկում։","result":"Ցուցանիշներն ու կանխատեսումը ստացվում են արտաքին API-ից։ Ինտերնետի կամ ծառայության խնդրի դեպքում ցուցադրվում է հաղորդագրություն՝ առանց օրինակային տվյալները որպես ընթացիկ եղանակ ներկայացնելու։","features":["Քաղաքի որոնում Geocoding API-ով","Ընթացիկ եղանակային ցուցանիշներ","Հնգօրյա կանխատեսում","Բեռնման և սխալի վիճակներ","Հին հարցումների չեղարկում","Վերջին քաղաքի պահպանում"]},
        music: {"category":"WEB AUDIO · DEMO","title":"Երաժշտական նվագարկիչ","summary":"Web Audio նվագարկիչ՝ երեք սինթեզված մեղեդով, իրական pause/resume-ով, ձայնի տեղափոխմամբ և ուժգնության կառավարմամբ։","challenge":"Բրաուզերում ստեղծել ձայն և մեղեդու ընտրությունը կապել ինտերֆեյսի հետ։","solution":"Մեղեդիները ստեղծվում են AudioBuffer-ներում։ BufferSource-ը սկսում է նվագարկումը ընտրված պահից, pause-ը կանգնեցնում է ձայնը, իսկ resume-ը շարունակում է նույն դիրքից։ Իրականացվել են ցանկից ընտրություն, ստեղնաշարի կառավարում և ձայնի ուժգնության փոփոխություն։","result":"Ժամանակը կապված է AudioContext-ի ժամացույցին։ Pause-ն ու սահիչը կառավարում են իրական ձայնը, մեղեդու ավարտից հետո սկսվում է հաջորդը։ Օգտագործվում են սինթեզված մեղեդիներ, ոչ թե արտաքին երաժշտական ֆայլեր։","features":["Ձայնի սինթեզ Web Audio-ով","Իրական pause և resume","Ձայնի տեղափոխում սահիչով","Մեղեդիների ընտրություն և հաջորդում","Ձայնի ուժգնության կառավարում","Ստեղնաշարով կառավարում"]}
    },
    en: {
        labels: ["← Back to projects", "Open demo ↗", "Challenge", "Solution", "Result", "What was built"],
        shop: { category: "E-COMMERCE · DEMO", title: "Modern Shop", summary: "A demo storefront with product search, category filters, and a cart with quantity controls, total calculation, and localStorage persistence.", challenge: "Help users find products, build a cart, and see an updated total after every change.", solution: "Implemented search by name, description, and category, category filters, adding and removing products, quantity controls, and total recalculation in JavaScript. Cart data is saved in localStorage.", result: "Users can find products, update their cart, and restore it after a reload. Checkout is a demonstration without payment or server-side order submission.", features: ["Search by name, description, and category", "Category filters", "Price and name sorting", "Add and remove products", "Quantity controls and total calculation", "Cart persistence with localStorage", "Demo checkout"] },
        planner: {"category":"REACT APP","title":"React Task Planner","summary":"A React planner with three pages, priorities, due dates, search, theme switching, and API example imports.","challenge":"A React planner with three pages, priorities, due dates, search, theme switching, and API example imports.","solution":"Components receive props, useState manages data, and useEffect handles persistence and API requests. Context shares tasks and theme, while React Router provides three routes. Forms support priorities, due dates, and validation.","result":"Tasks and theme persist locally. DummyJSON examples load with error handling and request cancellation. Duplicate imports are prevented, and personal tasks are not sent to the API.","features":["React components and props", "Strict TypeScript type checking","State, useState, and useEffect","Shared tasks and theme with Context","Three React Router pages","Priority and due-date form","Search and filters","API example imports","Local persistence and error handling"]},
        dashboard: { category: "DASHBOARD · DEMO", title: "Admin Dashboard", summary: "A demo dashboard with 7/30/90-day filtering, recalculated charts and metrics, an orders list, and CSV export.", challenge: "Organize metrics, sales, and orders into a clear layout for quick review.", solution: "JavaScript generates sample orders. Selecting 7, 30, or 90 days filters orders and recalculates metrics and chart values. Implemented full-list viewing, CSV export, and saved theme preferences.", result: "The chart, metrics, and table update from the same dataset for the selected period. Matching orders can be downloaded as CSV. Data is simulated and is not fetched from a server.", features: ["Key metric cards", "Sales bar chart", "Progress indicators", "Orders table", "Light and dark theme switching", "Period filtering and CSV export", "Order status filtering"] },
        weather: {"category":"WEATHER · API","title":"Weather App","summary":"City search, current weather indicators, and a five-day forecast from the Open-Meteo API.","challenge":"Handle city input and present clear weather indicators and error messages.","solution":"Geocoding resolves city coordinates before fetching current weather and a five-day forecast. Implemented loading states, error handling, and cancellation of outdated requests.","result":"Weather indicators and forecasts come from an external API. Connection failures display an error instead of presenting sample values as current weather.","features":["City search via Geocoding API","Current weather indicators","Five-day forecast","Loading and error states","Outdated request cancellation","Saved last city"]},
        music: {"category":"WEB AUDIO · DEMO","title":"Music Player","summary":"A Web Audio player with three synthesized melodies, working pause/resume, seeking, and volume control.","challenge":"Generate sound in the browser and connect melody selection to the interface.","solution":"Melodies are generated in AudioBuffers. BufferSource starts at the selected offset, pause stops audio, and resume continues from that position. Added playlist selection, keyboard controls, and volume adjustment.","result":"Playback time follows the AudioContext clock. Pause and seeking control actual sound, and the next melody starts on completion. Uses synthesized melodies rather than external music files.","features":["Web Audio synthesis","Working pause and resume","Audio seeking","Track selection and navigation","Volume control","Keyboard controls"]}
    }
};
const baseProject = caseStudies[projectId] || caseStudies.shop;
const project = { ...baseProject, ...(localizedContent[selectedLanguage]?.[projectId] || {}) };
const labels = localizedContent[selectedLanguage]?.labels || ["← Назад к проектам", "Открыть демо ↗", "Задача", "Решение", "Результат", "Что реализовано"];
document.title = `${project.title} | Case study`;
document.documentElement.lang = selectedLanguage;
document.querySelector(".back-link").textContent = labels[0];
document.getElementById("case-demo").textContent = labels[1];
document.querySelector(".case-grid .case-card:nth-child(1) h2").textContent = labels[2];
document.querySelector(".case-grid .case-card:nth-child(2) h2").textContent = labels[3];
document.querySelector(".case-grid .case-card:nth-child(3) h2").textContent = labels[4];
document.querySelector(".implementation h2").textContent = labels[5];
document.getElementById("case-category").textContent = project.category;
document.getElementById("case-title").textContent = project.title;
document.getElementById("case-summary").textContent = project.summary;
document.getElementById("case-challenge").textContent = project.challenge;
document.getElementById("case-solution").textContent = project.solution;
document.getElementById("case-result").textContent = project.result;
document.getElementById("case-demo").href = project.demo;
document.getElementById("case-tech").replaceChildren(...project.tech.map((item) => { const tag = document.createElement("span"); tag.textContent = item; return tag; }));
document.getElementById("case-features").replaceChildren(...project.features.map((item) => { const feature = document.createElement("li"); feature.textContent = item; return feature; }));
